In [2]:
import numpy as np
import pandas as pd

In [4]:
# escalar, vetor e matriz

#escalar - número (tensor de ordem 0)

x = 2 #escalar 
print(x)

x2 = np.array([1, 2, 3]) #vetor com 3 elementos escalares
print(x2)

x3 = np.array([[1], [2], [3]]) #matriz com 3 elementos vetores com elementos escalares
print(x3)

x4 = np.array([[1,2,3], [1,2,3], [1,2,3]]) #matriz tradicional quadrada
print(x4)


2
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
#normalmente usamos lista para muittas coisas, porém ele sugere usarmos mais dicionário 



lista = [1, 2, 3, 4, 5]

#df = pd.DataFrame(lista)
#df

df = pd.DataFrame({'coluna1': lista})
df
print(type(df))


#o que é o df? 'class 'pandas.core.frame.DataFrame', o df é uma tabela que é um df colunar que uma matriz, com vetores colunar 
#pandas series == vetor 
#dataframe = matriz
# LOGO, 
# AINDA PODERIAMOS criar esse df com:

array = np.array([1, 2, 3, 4, 5])
df = pd.DataFrame({'coluna1': array})
print(df)

# O pandas chama o vetor de SERIES

#OBSERVACAO para o type da coluna do df2, veremos que é um panda core SERIRES/SERIES, diferernte de frame/frame como antes.
#Porque, sabemos que a matriz é um conjunto de elementos vetores, então o df é uma matriz e cada coluna é um vetor E VETOR PRO PANDAS CHAMA SERIES.
df2 = pd.DataFrame({'coluna1': lista, 'coluna2': lista})
print(type(df2))
print(f'Mas se dermos o type na COLUNA de df2, veremos que é diferente do tipop do df e df2: {type(df2.coluna2)}')

print(df2)

<class 'pandas.core.frame.DataFrame'>
   coluna1
0        1
1        2
2        3
3        4
4        5
<class 'pandas.core.frame.DataFrame'>
Mas se dermos o type na COLUNA de df2, veremos que é diferente do tipop do df e df2: <class 'pandas.core.series.Series'>
   coluna1  coluna2
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5


In [20]:
# Para acessar os elementos:

# Exemplo em listas: 
print(lista[:1])

#No exemplo abaixo, 

[1]


In [21]:
#Video 5 
# Operacoes com vetores.  SOMA + SUBTRACAO

#Conseguimos fazer adicao, subtracao, log de vetores como conseguimos fazer com escalares? 
#Até o momento entendo a estrutura desses objetos. Mas vamos aprender as propriedades.

print(2/3)
# As propriedades que cercam os escalares devem ser preservadas. Pensemos que um escalar é um ponto, que nao posui dimensao. 
# Quando pensamos abrangentemente qualquer conceito matemático ele tem propriedades e axiomas (regras)
# se um escalar tem propriedades, elas devem ser extendidas a sua evolução, mas cada um com sua regra específica. Podemos somar um número, mas somaremos uma matriz de uma forma difirente. 

 

0.6666666666666666


In [23]:


print(x2)
print()
print(x3)
print()

# Fez combinação linear = é um somatório de elementos multiplicados entre si. 
# OBS = Como o vetor X2 e a matriz x3 não tem a mesma estrutura (um contem 3 escalares linha e a outra é uma matriz coluna, 
# a soma foi feita através de uma combinação linear

# Fez uma distributiva
# [1+1 = 2], [1+2 = 3], [1+3=4]
# [2+1 = 3], [2+2 = 4], [2+3= 5
# [3+1 = 4], [3+2 = 5], [3+3 = 6]
print(x2+x3)

# JÁ quando somamos duas matrizes 3x3 dobramos os valores, pois ele entende que a coluna 1 da primeira soma com a col 1 da segunda matriz e assim por diante

[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [26]:
x4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
# PENDENTE - PESQUISAR

# Operadores nao podem ser agrupados, pois um tem dimensao (2,1) e outro (3,3)

# Nesse caso temos um erro, pois aqui não temos a mesma quantidade de linhas para os dois arrays. A natureza se preserva quando temos o mesmo numero de linhas para colunas e etc

# A combinação linear entra a dica? o que vale para soma, vale ara - , combin linear pode ser subtracao. 

# Todo somatório pode se tornar um "somatório negativo quando multiplicamos por -1"

print(x4)

x5 = np.array([[1], [2]])
print(x5)
x5+x4

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1]
 [2]]


ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 

In [28]:
# MULTIPLICACAO 

#arr1 (x,y) / arr2 (z,w) --> y = z só podemos multiplicar quando temos o numero de colunas em 1 é == linhas em 2
# == arr3 (x, w)

#podemos usar:

np.dot(x3, x4)
# Esse erro demonstra isso.

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [34]:
# Mas e se trocarmos a ordem e colocar x4, x3
print(f'matriz x4 com : {x4}')
print()
print(f'matriz x3: {x3}', sep='\n')
print()

print(np.dot(x4, x3))

# Outra forma de multiplicar seria x4@x3

# Não temos o erro pois dessa vez o numero de colunas é igual ao numero de linhas 

# A ORDEM DOS FATORES ALTERA O PRODUTO DE MATRIZES, difente dos escalares. Dessa forma, :



matriz x4 com : [[1 2 3]
 [1 2 3]
 [1 2 3]]

matriz x3: [[1]
 [2]
 [3]]

[[14]
 [14]
 [14]]


In [35]:
# DIVISAO E EQUACAO FUNDAMENTAL DA ALGEBRA LINEAR 

# Pensando em que para acharmos o x na equacao abaixo isolamos o x. 
# 2.x = 4

x3/x5 # ERRO POIS NAO TEM A MESMA DIMENSAO

# MAS Pensando na divisao, considere:


# A . X = Y --> Para obtermos o x, poreríamos isalar o X? (# A . B != B . A (esse ponto não é a multiplicacao tradicional que vem com asterisco. Esse np.dot é produto interno de matrizes - um vetor x vetor = vetor ))
# Sim. X teria que ser uma matriz - é um vetor solucao com varios n;umeros

# ISSO AQUI É O CORACAO DA ALGEBRA. O motivo pela qual a algebra linear existe é essa equação
# Conhcemos o arcabouço teorico de algebra linear por causa dessa equação. Isso dará base para resolver problemas de ml 
# Isso deu base para resolver problema de equações que evoluiram no tempo - sistema chamado de processos markovianos ou cadeias de markov (analises de recorrencia como cadeias de markov e método dos mínimos quafrados)

# NOME - EQUACAO FUNDAMENTAL DA ALGEBRA LINEAR #################################


ValueError: operands could not be broadcast together with shapes (3,1) (2,1) 

In [ ]:
# A.X = Y ----> NÃO QUER DIZER QUE PARA QUE POSSAMOS ENCONTRAR O VETOR X, EU CONSIGA DIVIDIR Y POR A. 

# e aqui entra outro conceito, relacionado a matrizes especiais!!!

# pense:
# Na propriedade dos escalares conseguimos trocar o produto sem alterar o resultado: 
#1*0 = 0
#0*1 = 0 

# Já se fizermos 1/0, teremos um erro. 
# Dessa forma, o 0 para os escalares, NA SOMA E NA SUBTRAÇÃO, é o que chamamos de elemento neutro, pois nao afeta o resultado. 
# No caso da multiplicação e divisão o ELEMENTO NEUTRO É O 1

In [5]:
# Ainda pensando em multiplicação - PENSE EM UMA MATRIZ 3 X 3 

zeros = np.zeros((3,3))
ones = np.ones((3,3))
print(zeros)
print()
print(ones)

# A matriz só de UM é um elemento neutro no mundo das matrizes??? 
# NÃO, POIS VAI FAZER COMBINAÇÃO LINEAR E NÃO SERÁ NEUTRO

# pra ele preservar e ser realmente neutro, o um tem que estar em alguns locais estratégicos
#o indice da linha é o indice da coluna - quando definimos matriz temos:

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


$$A = pmatrix{a_{00} & a_{01} & a_{02} \\ a_{10} & a_{11} & a_{12} \\ a_{20} & a_{21} & a_{22}}$$

In [6]:
# MAS se eu quisesse multiplicar a matriz x4 POR um e quisesse preservar 
# quisesse PRESERVAR essa matriz, eu não poderia multiplicar por UMA MATRIZ DE 1 (sim, pelo escalar 1, preservaria, porém temos que falar de matriz identidade)
# pois aí eu teria uma combinação linear 
# pois eu teria multiplicacao da linha um com coluna 1 para termos o primiero termo (1 x 1 = 1 e 1+1+1+ = 3 e o resultado já mudou)
# se eu conseguisse preservar os elementos centrais da matriz (que no caso da matriz x4 é 1 2 3 ), dará certo, pois o 
# resto dos elementos vai zerar e na hora de multiplicar apenas 1 termo vai importar e outros vao zerar. 
# TENHO que preservar o 1 2 e 3 , e isso significa que a minha matriz de UM não precisa ter um em todo o lugar, mas NA DIAGONAL princial
# Então usamos a MATRIZ IDENTIDADE

id = np.eye(3)
# Se multiplicarmos o id*x4 teremos uma matriz com  1 2 3 (diagonal) e 0 nos demais locais
# ATENCÃO
# O que é interessa é que usamos essa um tipo de problema especifico
# Então estamos quase chegano no terorema fundamental da algebra - 

In [ ]:
# video 7/14

# NUMEROS INVERSOS
# PORQUE QUE O 1 É IMPORTANTE, elemento neutro e etc? Aqui entra um outro passo
# Número inverso não é ser positivo ou negativo
# se um número é inverso do outro, um número vezes seu inverso tem que dar 1 (propriedade)
# EX: quem é o inverso de 1
# Para isso, temos que 

# um numero que multiplica seu inverso tem que dar 1 
# abaixo x.x elevado na menos um (quer dizer, inverso) tem que dar um
# O UM é o elemento neutro // elemento identidade // matriz identidade , np.eye

#supondo que x seja uma matriz, e 1 seja uma matriz identidade

$$x . x^{-1} = 1$$

---

$$A . A^{-1} = 1$$ 

---
Eq. Fundamental da Álgebra 
$$A. X = Y$$

Uma triz quadrada . uma matriz icognita = matriz y 

In [ ]:
# Esse A-1 vai ter um nome (se escalares, vetores e matrizes tudo é um tensor, entao a propriedade deve se estender, também para os numeros inversos)

# entao a propriedade do numero inverso tem que estender para matrizes, entao como é o nome dessa matriz A-1 == MATRIZ INVERSA

# OU SEJA, uma matriz vezes a sua inversa dará a matriz identidade e essa premissa ajuda no teprema fundamental da algebra. 

# se eu consigo definir uma matriz identidade, entao a matriz id vezes uma matriz, nao deveria adulterar o seu resultado (desde que o que eu multiplico de um lado, eu possa multiplicar do outro)

#desde que: 

$$A.aˆ{-1}.X = Aˆ{-1}.Y$$
Se eu considderar que $$ A.Aˆ{-1}$$ é a matriz identidade, por consequencia x = a elevado a menos 1 . y:

$$X = Aˆ{-1}.Y$$
E essa é a solução para a equação da algebra fundamental (se A for quadrada)
A equação 1 e 3 fundamentam sistemas lineares 

Quando temos matrizes não quadradas, não usamos matriz inversa para resolver. Usamos pseudo matriz inversa. 

In [2]:
# Video 8
# Quando A não é quadrada, n consigo falar q tem inversa. 
# Usamos matriz pseudo inversa 
# A elevado a T (T é a matriz transposta)
# Quando não temos uma matriz quadrada, multiplicamos ela pela transposta e achamos uma matriz quadrada
# Fazemos uma correcao linear, com a transposta achando um valor muito proximo do que seria A 

# É a equação abaixo que resolve, por ex, problemas como metodo dos minimos quadrados, que resolve problemas de interpolação de retas
# PORQUE e como sabemos dar o import certo? 

# Porque temos que plotar um reta? Fazemos isso, quando? Que tipo de problemas envolvem plotar uma reta ? em problemas cuja solucao, 
# envolvem uma EQUACAO DO PRIMEIRO GRAU 
# Só que MUITAS das vezes uma REGRESSÃO não resolve o problema

# é o algoritmo mais simples no aprendizado de máquina. O que é o aprendizado de máquina na matematica?
# Com base nessa distribuição de pontos. Não é que o algoritmo aprendeu. Com base na distruibuição de pontos que foi fornecido, ele segue 
# Um padrão matemático. Nesse caso, forçamos a ser uma reta. Não falamos, aaaahhh, ache a função livremente. Não, eu pressupuz que o meu problema 
# como solução é uma reta - e por isso, usei aquele método.
# Mas se eu palasse ajuste usando um polinomio do segundo grau - a função mudaria ( A MATRIZ A usada, mudaria e por conseeguencia toda a formulacao.
# 
# Entao temos que saber como atuar / o aprendizado de máquina (usamos essa palavra aprendizado, fazemos uma correlação com IA, mas na verdade
# o do modelo idetnifica padroes e traz uma funcao que melhor descreve o padrao (NÃO É BEM A QUE MELHOR DESCREVE. Corrigindo, TRAZ uma função ue melhor se aproxima do ideal)
# Então, aqui estamos pressupondo que é linear !!! então estudamos uma frequencia de distribução de pontos que é muitooo caotica, imagina! 
# Aqui usamos uma funcao linear... nem analizamos coisas mais profundas, como por ex, É UMA DISTRIBUIÇÃO NORMAL/gaussiana? ela preserva media, mediana e moda?
# sendo a mesma coisa que uma dis. normal? 
# ou será que tenho que modelar com um tipo de distribuição diferente bnomila, poisson, entre outras, que trarão resultados diferentes. 
# Nesse contexto, podemos dizer qu eé a estatistica que dá corpo pra a algebra linear

# Pensando em estatística devemos pensar ... será que temos alguns pontos que estão atrapalhando na minha previsão (outlieers?) ou será que esses pontos estão fora, mas são informativos?
# preciso entender se meus dados estão próximos ou distantes do que eu chamo de desvio paddrao (que é a medida de dispersão em torno da média) 
# Ou se a minha distribuição probabilistica vai fazer com que eu tenha que usar argumentos um pouco MENOS conservadores, como métodos de monte carlo
# de probabilidade estatista, pois não conhecemos uma série de parâmetros do nosso problema e etc!! ANOTAR 


Matriz pseudo inversa 

$$X = (A^{T}A)^{-1}A^{T}Y$$


In [ ]:
# VIDEO 9 DE Estatatistica e algenil em python 

# Quando estamos modelando machine learning muitas vezes esquecemos que estamos trabalhando com a teoria dos conjuntos. 
# Quando vamos prever a temperatura, por ex, temos a umidade do ar, pressar e temp. Teremos infinitas combinacoes dessas variaves (existe uma escala de umidade, escala de temp e etc). 
# Se fizermos uma combinação teriamos muitoos valores, podemos comentar algo interessante aqui que o humano nao lida bem. 
# que é o conceito de variavel discreta e continua na estatistica. Por exemplo, quando usamos uma contagem (inteira), mas temperaturas podem ser float 
# entao a base da estatistica esta em conceitos simples... que sao os conceitos basais, 

# POR EXEMPLO esstamos prevendo preços DE venda, no momento de fazer feature engeneering para valores nulos.
# Será que faz sentido preencher o que está nulo com a média de venda - será que a média é um valor interessante para trabalhar?
# Tudo depende SE OS DADOS SEguem uma dist normal (aquela regra que temos la com valores centrais até 68,5%, depois disso vai p 95 alguma coisa e depois para 99.8 ai temos intervalos do z scores 
# talvez faça sentido.)
# Mas ai se tiver um outlier 
# Por exemplo estamos vendendo monitores a media depreco é 100... mas tem um monitor que é 300. o que isso vai fazer? 
# já da pra responder que ele vai alterar o comportamento alterando a media (dependendo do valor se estamos trabalhando com positivos ou negativos)
# AH qual seria a alternativa?? temos a mediana... a depender tb do tipo de dado que temos ali 

#tudo nasce d estatistica e incerteza 