In [5]:
import numpy as np
import pandas as pd

In [4]:
# escalar, vetor e matriz

#escalar - número (tensor de ordem 0)

x = 2 #escalar 
print(x)

x2 = np.array([1, 2, 3]) #vetor com 3 elementos escalares
print(x2)

x3 = np.array([[1], [2], [3]]) #matriz com 3 elementos vetores com elementos escalares
print(x3)

x4 = np.array([[1,2,3], [1,2,3], [1,2,3]]) #matriz tradicional quadrada
print(x4)


2
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
#normalmente usamos lista para muittas coisas, porém ele sugere usarmos mais dicionário 

#o que é o df? 'class 'pandas.core.frame.DataFrame', o df é uma tabela que é um df colunar que uma matriz, com vetores colunar 

lista = [1, 2, 3, 4, 5]

#df = pd.DataFrame(lista)
#df

df = pd.DataFrame({'coluna1': lista})
df
print(type(df))

<class 'pandas.core.frame.DataFrame'>
