In [5]:
import numpy as np
import pandas as pd

In [4]:
# escalar, vetor e matriz

#escalar - número (tensor de ordem 0)

x = 2 #escalar 
print(x)

x2 = np.array([1, 2, 3]) #vetor com 3 elementos escalares
print(x2)

x3 = np.array([[1], [2], [3]]) #matriz com 3 elementos vetores com elementos escalares
print(x3)

x4 = np.array([[1,2,3], [1,2,3], [1,2,3]]) #matriz tradicional quadrada
print(x4)


2
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [18]:
#normalmente usamos lista para muittas coisas, porém ele sugere usarmos mais dicionário 



lista = [1, 2, 3, 4, 5]

#df = pd.DataFrame(lista)
#df

df = pd.DataFrame({'coluna1': lista})
df
print(type(df))


#o que é o df? 'class 'pandas.core.frame.DataFrame', o df é uma tabela que é um df colunar que uma matriz, com vetores colunar 
#pandas series == vetor 
#dataframe = matriz
# LOGO, 
# AINDA PODERIAMOS criar esse df com:

array = np.array([1, 2, 3, 4, 5])
df = pd.DataFrame({'coluna1': array})
print(df)

# O pandas chama o vetor de SERIES

#OBSERVACAO para o type da coluna do df2, veremos que é um panda core SERIRES/SERIES, diferernte de frame/frame como antes.
#Porque, sabemos que a matriz é um conjunto de elementos vetores, então o df é uma matriz e cada coluna é um vetor E VETOR PRO PANDAS CHAMA SERIES.
df2 = pd.DataFrame({'coluna1': lista, 'coluna2': lista})
print(type(df2))
print(f'Mas se dermos o type na COLUNA de df2, veremos que é diferente do tipop do df e df2: {type(df2.coluna2)}')

print(df2)

<class 'pandas.core.frame.DataFrame'>
   coluna1
0        1
1        2
2        3
3        4
4        5
<class 'pandas.core.frame.DataFrame'>
Mas se dermos o type na COLUNA de df2, veremos que é diferente do tipop do df e df2: <class 'pandas.core.series.Series'>
   coluna1  coluna2
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5


In [20]:
# Para acessar os elementos:

# Exemplo em listas: 
print(lista[:1])

#No exemplo abaixo, 

[1]


In [21]:
#Video 5 
# Operacoes com vetores. 

#Conseguimos fazer adicao, subtracao, log de vetores como conseguimos fazer com escalares? 
#Até o momento entendo a estrutura desses objetos. Mas vamos aprender as propriedades.

print(2/3)
# As propriedades que cercam os escalares devem ser preservadas. Pensemos que um escalar é um ponto, que nao posui dimensao. 
# Quando pensamos abrangentemente qualquer conceito matemático ele tem propriedades e axiomas (regras)
# se um escalar tem propriedades, elas devem ser extendidas a sua evolução, mas cada um com sua regra específica. Podemos somar um número, mas somaremos uma matriz de uma forma difirente. 

 

0.6666666666666666


In [23]:


print(x2)
print()
print(x3)
print()

# Fez combinação linear = é um somatório de elementos multiplicados entre si. 
# OBS = Como o vetor X2 e a matriz x3 não tem a mesma estrutura (um contem 3 escalares linha e a outra é uma matriz coluna, 
# a soma foi feita através de uma combinação linear

# Fez uma distributiva
# [1+1 = 2], [1+2 = 3], [1+3=4]
# [2+1 = 3], [2+2 = 4], [2+3= 5
# [3+1 = 4], [3+2 = 5], [3+3 = 6]
print(x2+x3)

# JÁ quando somamos duas matrizes 3x3 dobramos os valores, pois ele entende que a coluna 1 da primeira soma com a col 1 da segunda matriz e assim por diante

[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [26]:
x4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
# PENDENTE - PESQUISAR

# Operadores nao podem ser agrupados, pois um tem dimensao (2,1) e outro (3,3)

# Nesse caso temos um erro, pois aqui não temos a mesma quantidade de linhas para os dois arrays. A natureza se preserva quando temos o mesmo numero de linhas para colunas e etc

# A combinação linear entra a dica? o que vale para soma, vale ara - , combin linear pode ser subtracao. 

# Todo somatório pode se tornar um "somatório negativo quando multiplicamos por -1"

print(x4)

x5 = np.array([[1], [2]])
print(x5)
x5+x4

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1]
 [2]]


ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 